class Common:

    # マスの数
    MASS_NUM = 7

    # 最大ターン数
    MAX_TURN = 30

    # 最大対戦数
    MAX_GAME_COUNT = 5

    # 戦闘時の勝利確率
    WINNING_PERCENTAGE_VERY_GOOD    = 80    # 相性が強い場合の勝利確率
    WINNING_PERCENTAGE_GOOD         = 60    # 相性がやや強い場合の勝利確率

    # ここから下はGUI用
    MASS_SIZE = 80
    GAME_CANVAS_WIDTH = MASS_SIZE * MASS_NUM
    GAME_CANVAS_HEIGHT = MASS_SIZE * MASS_NUM
    STATUS_CANVAS_WIDTH = GAME_CANVAS_WIDTH
    STATUS_CANVAS_HEIGHT = 80
    WINDOW_WIDTH = GAME_CANVAS_WIDTH
    WINDOW_HEIGHT = GAME_CANVAS_HEIGHT + STATUS_CANVAS_HEIGHT

